name: Generate CatCast M3U

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.14"
      - name: Install requests
        run: pip install requests
      - name: Run M3U Generator
        run: python generate_playlist.py
      - name: Upload M3U artifact
        uses: actions/upload-artifact@v4   # <-- v4 ile gÃ¼ncelledik
        with:
          name: catcast_tv_m3u
          path: catcast_tv.m3u
